spring:
  mongodb:
    uri: mongodb://admin:admin123@localhost:27017/fitness_activity?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka:
  topic:
    name: activity-events

eureka:
  client:
    register-with-eureka: true   # Eureka pe register kare
    fetch-registry: true         # dusri services ko fetch kare
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

